// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb6ihnr-QxCKjUVfCN-BA0R8B0a4P0IxI',
    appId: '1:43761353988:web:8d0d5a040ee7d2a65b3c51',
    messagingSenderId: '43761353988',
    projectId: 'uninest-app-1',
    authDomain: 'uninest-app-1.firebaseapp.com',
    storageBucket: 'uninest-app-1.firebasestorage.app',
    measurementId: 'G-9GFF4GFWY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsCJlPpF0_auPJkdWTLUADpsSxOeDLqzg',
    appId: '1:43761353988:android:18a926834549052d5b3c51',
    messagingSenderId: '43761353988',
    projectId: 'uninest-app-1',
    storageBucket: 'uninest-app-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPJ7l4CDOwtsIgAcclQMpdWkSivKiFTQA',
    appId: '1:43761353988:ios:a4fe107f8fdebd3d5b3c51',
    messagingSenderId: '43761353988',
    projectId: 'uninest-app-1',
    storageBucket: 'uninest-app-1.firebasestorage.app',
    iosClientId: '43761353988-7sqr3j40s3anr1nfopsin5shpfv4g0v2.apps.googleusercontent.com',
    iosBundleId: 'com.example.uninestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPJ7l4CDOwtsIgAcclQMpdWkSivKiFTQA',
    appId: '1:43761353988:ios:a4fe107f8fdebd3d5b3c51',
    messagingSenderId: '43761353988',
    projectId: 'uninest-app-1',
    storageBucket: 'uninest-app-1.firebasestorage.app',
    iosClientId: '43761353988-7sqr3j40s3anr1nfopsin5shpfv4g0v2.apps.googleusercontent.com',
    iosBundleId: 'com.example.uninestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb6ihnr-QxCKjUVfCN-BA0R8B0a4P0IxI',
    appId: '1:43761353988:web:f4eb261fa7228db65b3c51',
    messagingSenderId: '43761353988',
    projectId: 'uninest-app-1',
    authDomain: 'uninest-app-1.firebaseapp.com',
    storageBucket: 'uninest-app-1.firebasestorage.app',
    measurementId: 'G-MY89W43W2V',
  );
}
